version: "3.4"

services:
  cen:
    build:
      context: ../../..
      dockerfile: node/Dockerfile
      target: builder
    container_name: cen-node
    command:  "sh -c \"cd app && fresh\" "
    volumes:
      - ../..:/go/src/gitlab.com/velo-labs/cen
    ports:
      - "8080:8080"
    environment:
      HORIZON_URL: "https://horizon-testnet.stellar.org"
      DRS_ADDRESS: "GABB2XA6ROY6IZWP2EKD3JIW3KMT6EYAWJMPR7DYWQ3F64BEC7NPLEQS"
      DRS_PRIVKEY: "SANRCZEEE3JNSWJCTDFPCKKZJYQBM45QYFIK3J52UHD7LB5A2TQVL6YI"
      VELO_ISSUER_ADDRESS: "GCV3Q6QZZUG7RWPIQ5CZ5MOW3KBBCQYT64EIQX6GVKDQL27WOYNDQD3G"
      NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
      LEVEL_DB_PATH: "./databases/leveldb/.data/node.db"
      CREDIT_PREFIX: "0x0000"
      PRICE_FEED_PREFIX: "0x0001"
      PRICE_PREFIX: "0x0002"
