version: "3.4"

services:
  cen:
    build:
      context: ../../..
      dockerfile: node/Dockerfile
      target: development
    container_name: cen-node
    command:  sh -c 'cd node/app && fresh'
    volumes:
      - ../../..:/go/src/gitlab.com/velo-labs/cen
      - $GOPATH/pkg/mod:/go/pkg/mod # to avoid re-"go mod download" on every build
    ports:
      - "8080:8080"
      - "6666:6666"
    environment:
      HORIZON_URL: "https://horizon-testnet.stellar.org"
      DRS_PUBLIC_KEY: "GB7QJFBQ7WABQ5EZ2XR5XEJOUUYMBJOOLJHCBNZO462P2XRPSJ7TZJXA"
      DRS_SECRET_KEY: "SDQ5OR2EZIGOGZQNLIAQKMX2Q42WF54L5YVXRHLVYGP2UNSSPRYJS6FA"
      VELO_ISSUER_PUBLIC_KEY: "GCV3Q6QZZUG7RWPIQ5CZ5MOW3KBBCQYT64EIQX6GVKDQL27WOYNDQD3G"
      NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
