version: "3.4"

services:
  cen:
    build:
      context: ../../..
      dockerfile: node/Dockerfile
      target: development
    container_name: cen-node
    command:  sh -c 'cd node/app && fresh'
    volumes:
      - ../../..:/go/src/gitlab.com/velo-labs/cen
      - $GOPATH/pkg/mod:/go/pkg/mod # to avoid re-"go mod download" on every build
    ports:
      - "8080:8080"
      - "6666:6666"
    environment:
      HORIZON_URL: "https://horizon-testnet.stellar.org"
      DRS_PUBLIC_KEY: "GB5T256VCCM5NXVEMM6LCSIGNDRQEX6JRY3UUCUSKTROST4UZBH5D2EZ"
      DRS_SECRET_KEY: "SCFI5WS22R6BHNRJ6PKV3UF5PUHTDPCX7WL52GGB5IGTQAMOJAPTYCCG"
      VELO_ISSUER_PUBLIC_KEY: "GC3COBQESTRET2AXK5ADR63L7LOMEZWDPODW4F2Z7Y44TTEOTRBSKXQ3"
      NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
