version: "3.4"

services:
  cen:
    build:
      context: ../../..
      dockerfile: node/Dockerfile
      target: builder
    container_name: cen-node
    command:  sh -c 'cd node/app && fresh'
    volumes:
      - ../../..:/go/src/gitlab.com/velo-labs/cen
      - $GOPATH/pkg/mod:/go/pkg/mod
    ports:
      - "8080:8080"
    environment:
      HORIZON_URL: "https://horizon-testnet.stellar.org"
      DRS_ADDRESS: "GABB2XA6ROY6IZWP2EKD3JIW3KMT6EYAWJMPR7DYWQ3F64BEC7NPLEQS"
      DRS_PRIVKEY: "SANRCZEEE3JNSWJCTDFPCKKZJYQBM45QYFIK3J52UHD7LB5A2TQVL6YI"
      VELO_ISSUER_ADDRESS: "GCV3Q6QZZUG7RWPIQ5CZ5MOW3KBBCQYT64EIQX6GVKDQL27WOYNDQD3G"
      NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
      CREDIT_PREFIX: "0x0000"
      PRICE_FEED_PREFIX: "0x0001"
      PRICE_PREFIX: "0x0002"
      POSTGRES_HOST: postgres-cen-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cen_db
  postgres-cen-db:
    image: "postgres:11.5-alpine"
    container_name: postgres-cen-db
    volumes:
      - ./postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./postgres/db:/var/lib/postgresql/data
    restart: 'always'
    expose:
      - 5432
    ports:
      - "5432:5432"

  pgadmin:
    image: chorss/docker-pgadmin4
    depends_on:
      - postgres-cen-db
    ports:
      - 5050:5050
