version: "3.4"

services:
  cen:
    build:
      context: ../../..
      dockerfile: node/Dockerfile
#      target: development
    container_name: cen-node
    command:  sh -c 'cd node/app && fresh'
    volumes:
      - ../../..:/go/src/gitlab.com/velo-labs/cen
      - $GOPATH/pkg/mod:/go/pkg/mod # to avoid re-"go mod download" on every build
    ports:
      - "8080:8080"
    environment:
      HORIZON_URL: "https://horizon-testnet.stellar.org"
      DRS_PUBLIC_KEY: "GCQCXIDTFMIL4VOAXWUQNRAMC46TTJDHZ3DDJVD32ND7B4OKANIUKB5N"
      DRS_SECRET_KEY: "SDE374OE44ZU73KAUFYPNMQEUGCDIJLTIIUZ4W2MKWBPPAK36ID26ECU"
      VELO_ISSUER_PUBLIC_KEY: "GCV3Q6QZZUG7RWPIQ5CZ5MOW3KBBCQYT64EIQX6GVKDQL27WOYNDQD3G"
      NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
