version: "3.4"

services:
  cen:
    build:
      context: ../../..
      dockerfile: node/Dockerfile
      target: development
    container_name: cen-node
    command:  sh -c 'cd node/app && fresh'
    volumes:
      - ../../..:/go/src/gitlab.com/velo-labs/cen
      - $GOPATH/pkg/mod:/go/pkg/mod # to avoid re-"go mod download" on every build
    ports:
      - "8080:8080"
      - "6666:6666"
    environment:
      HORIZON_URL: "https://horizon-testnet.stellar.org"
      DRS_PUBLIC_KEY: "GADY65NKSSPA4RPUNLXM3UM27KXUG5O52YVA763GQ47B26AW4CW4TY45"
      DRS_SECRET_KEY: "SBYKBAPJOCV6MLZ5Z6IH2KBSRYF24HSGGLXVH7TK7TOWTH3LHI5JJJB3"
      VELO_ISSUER_PUBLIC_KEY: "GC3COBQESTRET2AXK5ADR63L7LOMEZWDPODW4F2Z7Y44TTEOTRBSKXQ3"
      NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
