version: "3.4"

services:
  cen:
    build:
      context: ../../..
      dockerfile: node/Dockerfile
      target: development
    container_name: cen-node
    command:  sh -c 'wait-for postgres-cen-db:5432 --timeout=60 && cd node/app && fresh'
    volumes:
      - ../../..:/go/src/gitlab.com/velo-labs/cen
      - $GOPATH/pkg/mod:/go/pkg/mod # to avoid re-"go mod download" on every build
    ports:
      - "8080:8080"
    environment:
      HORIZON_URL: "https://horizon-testnet.stellar.org"
      DRS_PUBLIC_KEY: "GABB2XA6ROY6IZWP2EKD3JIW3KMT6EYAWJMPR7DYWQ3F64BEC7NPLEQS"
      DRS_SECRET_KEY: "SANRCZEEE3JNSWJCTDFPCKKZJYQBM45QYFIK3J52UHD7LB5A2TQVL6YI"
      VELO_ISSUER_PUBLIC_KEY: "GCV3Q6QZZUG7RWPIQ5CZ5MOW3KBBCQYT64EIQX6GVKDQL27WOYNDQD3G"
      NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
      POSTGRES_HOST: postgres-cen-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cen_db

  postgres-cen-db:
    image: "postgres:11.5-alpine"
    container_name: postgres-cen-db
    volumes:
      - ./postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./postgres/db:/var/lib/postgresql/data
    restart: 'always'
    expose:
      - 5432
    ports:
      - "5432:5432"